# Generated by Django 3.2.17 on 2023-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=8, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=2000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
